name: Terraform Deployment

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

permissions:
  id-token: write  # Needed for OIDC authentication
  contents: read

jobs:
  terraform-deploy:
    name: Terraform Check, Plan, and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Run terraform fmt
        run: terraform fmt -check

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
          role-session-name: GitHubActionsTerraform
          aws-region: eu-west-2

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Run Terraform Plan
        run: terraform plan

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
